# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 29 Oct 2025 12:39:18 +0100
*               @ALL          1
*               @user         8
