<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Wed, 29 Oct 2025 12:39:18 +0100
 */
$conf['title'] = 'Драконы и драконы';
$conf['lang'] = 'ru';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
