# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 29 Oct 2025 12:39:18 +0100
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$XSSUbYbtZUSOyz3o4HPWjOSK9TKmO/YdpJW/TOPWixmFMxf4aijVG:Роман:roma199696@yandex.ru:admin,user
